### PR TITLE
rebar3 updates

### PR DESCRIPTION
**Pull request by tsloughter**
This pr adds the metadata for a hex package when published and updates the config for rebar3.

### CODE REVIEW

**Comment by tsloughter** [comment]
OTP's older than 18 are failing because of use of `rand`. I guess I can add a compile flag.

**Comment by darach** [comment]
Hi Tristan,

Sorry for the radio silence. A check/flag or wrapping the underlying
call so that it can switch as appropriate would be fine.

Cheers,

Darach.

**Comment by tsloughter** [comment]
Cool, I've updated it.

OK if I publish to hex myself once this is merged?

**Comment by darach** [comment]
LGTM. Merging. Publish away on hex.

**Comment by darach** [comment]
Tagged 0.2.2

**Pull request merged**
